Closes #17 create/ getAll check lists (server side)
ss-ita/checklisty-server pull request #21
Opened 2019-02-01 13:40 UTC by angelikaSemeniuk

2019-02-01 13:41 UTC, OBats approved these changes

2019-02-01 14:41 UTC, Antoniozinchenko requested changes

2019-02-01 14:41 UTC, Antoniozinchenko commented on api/controllers/checklist-controler.js
> +    console.log("action-getAll");
remove console.log

2019-02-01 14:41 UTC, Antoniozinchenko commented on api/controllers/checklist-controler.js
> +                item_data: doc.map(item => {
doc.item_data.map( ...

2019-02-01 14:41 UTC, Antoniozinchenko commented on api/controllers/checklist-controler.js
> +                author: doc.author.username,
doc.author.username is undefined in your case 
just leave  **author: doc.author**

2019-02-03 12:52 UTC, Antoniozinchenko approved these changes

2019-02-03 13:34 UTC, romanolytvyn approved these changes

2019-02-03 20:48 UTC, rostyslav-vasyliuk approved these changes

2019-02-04 08:40 UTC, Roman6917 approved these changes

2019-02-04 08:43 UTC, merged