Closes #3 check list CRUD (server side)
ss-ita/checklisty-server pull request #23
Opened 2019-02-02 17:22 UTC by angelikaSemeniuk

create checkList
create checkListItem
getOne
update
delete

2019-02-02 18:47 UTC, OBats approved these changes
Well done!

2019-02-03 10:40 UTC, romanolytvyn approved these changes

2019-02-03 12:44 UTC, Antoniozinchenko requested changes

2019-02-03 12:44 UTC, Antoniozinchenko commented on api/controllers/checklist-controler.js
> +            if(item.id === req.params.itemid) {
item.id is not exist, condition always be false

2019-02-03 12:44 UTC, Antoniozinchenko commented on api/controllers/checklist-controler.js
> +        const { title, description, tag, category, priority } = req.body;
looks like you going to update just one checklist item,
would be better to update whole item_data array

2019-02-04 12:15 UTC, Antoniozinchenko approved these changes

2019-02-04 12:24 UTC, machikharostyk approved these changes

2019-02-04 12:24 UTC, rostyslav-vasyliuk approved these changes

2019-02-04 13:05 UTC, merged

2019-02-04 14:00 UTC, AndriyTykhan commented on api/controllers/checklist-controler.js
> +
You could write just like this: 
list.item_data.push({
            title,
            description,
            ...
        });

2019-02-04 14:00 UTC, AndriyTykhan commented on api/controllers/checklist-controler.js
> +
Maybe it would be better if something is absent, just take old property

2019-02-04 14:00 UTC, AndriyTykhan commented on api/models/checklist-item-model.js
> +module.exports = { checklistItemSchema, ChecklistItemModel };
Do you need ChecklistItemModel ? If no maybe better delete it

2019-02-04 14:00 UTC, AndriyTykhan commented on api/routes/checklists-routers.js
> +
if you write something like this:
`router.get('/:id', checklistControler.getOne);`
In such case for all just write  `router.get('/', checklistControler.getAll);`

2019-02-04 14:00 UTC, AndriyTykhan commented on api/routes/checklists-routers.js
> +module.exports = router;
Aslo you maybe will need get all list, and get all my list or somenthing like this