minor fixes
ss-ita/checklisty-server pull request #24
Opened 2019-02-04 10:20 UTC by romanolytvyn

2019-02-04 16:24 UTC, AndriyTykhan approved these changes

2019-02-04 19:57 UTC, Antoniozinchenko requested changes
Frontend issue. not valid fix

2019-02-04 20:17 UTC, anzhelikavelychko approved these changes

2019-02-05 17:46 UTC, rostyslav-vasyliuk approved these changes

2019-02-06 10:37 UTC, closed without merging