Close #20 - User cabinet
ss-ita/checklisty-server pull request #26
Opened 2019-02-04 13:22 UTC by machikharostyk

2019-02-04 19:28 UTC, rostyslav-vasyliuk approved these changes

2019-02-04 19:31 UTC, Antoniozinchenko requested changes

2019-02-04 19:31 UTC, Antoniozinchenko commented on api/controllers/profile-cotroller.js
> +        const updateUserInfo = await User.findByIdAndUpdate(id, { user });
use $set operator: findByIdAndUpdate(id, {$set: user })
https://docs.mongodb.com/manual/reference/operator/update/set/

2019-02-04 19:31 UTC, Antoniozinchenko commented on api/controllers/profile-cotroller.js
> +        const {password, ...user} = await User.findById({ id });
just pass id, not { id }
await User.findById(id);

2019-02-05 10:06 UTC, Antoniozinchenko approved these changes

2019-02-05 11:34 UTC, anzhelikavelychko approved these changes

2019-02-05 11:39 UTC, OBats approved these changes

2019-02-05 11:44 UTC, Roman6917 approved these changes

2019-02-05 11:51 UTC, merged