Closes #42 - Add profile editing to backend
ss-ita/checklisty-server pull request #43
Opened 2019-02-19 15:39 UTC by Yuri-Pristay

2019-02-20 12:09 UTC, anzhelikavelychko approved these changes

2019-02-20 12:10 UTC, romanolytvyn approved these changes

2019-02-20 12:11 UTC, rostyslav-vasyliuk approved these changes

2019-02-20 12:31 UTC, OBats approved these changes

2019-02-21 11:04 UTC, Roman6917 approved these changes

2019-02-23 09:43 UTC, Antoniozinchenko requested changes

2019-02-23 09:43 UTC, Antoniozinchenko commented on api/controllers/profile-cotroller.js
> +        const userSchema = mongoose.Schema({
why userSchema is in controller???? o_0

2019-02-23 09:43 UTC, Antoniozinchenko commented on api/controllers/profile-cotroller.js
> +        if (user.username === req.body.name) await User.findByIdAndUpdate(
use **$set**  for updating multiple fields
https://stackoverflow.com/questions/37267042/mongoose-findoneandupdate-updating-multiple-fields

2019-02-25 15:43 UTC, AndriyTykhan approved these changes

2019-02-25 18:09 UTC, romanolytvyn approved these changes

2019-02-25 19:26 UTC, Antoniozinchenko approved these changes

2019-02-26 14:33 UTC, merged