Add pagination logic at back-end
ss-ita/checklisty-server pull request #71
Opened 2019-03-07 17:39 UTC by machikharostyk

2019-03-07 21:46 UTC, Antoniozinchenko approved these changes

2019-03-08 08:36 UTC, OBats requested changes

2019-03-08 08:36 UTC, OBats commented on api/controllers/checklist-controler.js
> -        slug: doc.slug,
Please don't remove `slug`. I need it on a demo 😈

2019-03-08 08:36 UTC, OBats commented on api/controllers/checklist-controler.js
> -        slug: doc.slug,
The same.

P.S. seems you have some issues with indents.

2019-03-08 09:40 UTC, rostyslav-vasyliuk approved these changes

2019-03-08 09:41 UTC, AndriyTykhan approved these changes

2019-03-08 09:42 UTC, OBats approved these changes

2019-03-08 09:42 UTC, anzhelikavelychko approved these changes

2019-03-08 09:45 UTC, merged